name: Notify Discord on Push  
on:
  push:
    branches:
      - frontend  # 'frontend' 브랜치에 푸시될 때만 실행
  workflow_dispatch:  # 수동 실행을 위한 설정 추가

jobs:
  discord_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        run: |
          echo "GITHUB_REF_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GITHUB_COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV

      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                    "username": "GitHub Bot",
                    "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                    "embeds": [
                      {
                        "title": "푸시 알림",
                        "description": "**브랜치**          **커밋 작성자**\n'"$GITHUB_REF_NAME"'         '"$GITHUB_ACTOR"'\n\n**커밋 메시지**\n'"$GITHUB_COMMIT_MESSAGE"'",
                        "color": 3381759,
                        "thumbnail": {
                          "url": "https://i.postimg.cc/SNQjYtv8/vt-logo.png"
                        },
                        "footer": {
                          "text": "GitHub Actions - 자동 알림"
                        },
                        "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
                      }
                    ]
                  }' \
               $DISCORD_WEBHOOK_URL
